# Start from the GeoServer image
FROM docker.osgeo.org/geoserver:2.25.x

# Your customizations go here
# For example, you might want to set environment variables,
# install additional tools, copy configuration files, etc.

# Example: Setting an environment variable
# ENV MY_CUSTOM_ENV_VAR=my_value

# Example: Copying a custom GeoServer data directory into the container
# COPY my_geoserver_data_dir /geoserver_data_dir

# No CMD or ENTRYPOINT is necessary if you're just using the base image's setup,
# but you can override or specify them if needed.
